CREATE DATABASE EVENTOS;
USE EVENTOS;

CREATE TABLE tbEventos (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    local VARCHAR (50) NOT NULL,
    data_hora DATETIME NOT NULL
);

CREATE TABLE tbEscalas (
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    funcionario VARCHAR(50) NOT NULL,
    funcao VARCHAR(20) NOT NULL,
    CPF VARCHAR(20) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    id_evento INTEGER NOT NULL,
    FOREIGN KEY (id_evento) REFERENCES tbEventos(id)
);

